### ISSUE TITLE
Import API from File/Clipboard fails with a Java error

### ISSUE THREAD

**Issue by GBR-613** [Apicurio/apicurio-studio#1969] opened 2022-07-28 15:08 UTC
The following exception occurs when I paste the content and press on "Import API" button:

org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'                                                                                              
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:82)                                                            
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:346)                                                                      
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:193)       
        ...
        
According [to the following](https://stackoverflow.com/questions/70422060/object-mapper-yamlfactory-exception-due-to-missing-createcontentreference-m), jackson-core.2.13.0.jar or later should be used.  When I look for jars with similar names, I see them all 2.13.2, excluding the following:
modules/system/layers/base/com/fasterxml/jackson/core/jackson-core/main/jackson-core-2.9.9.jar        

I think this is the cause of the error. When I pushed jackson-core-2.9.9.jar aside and copied jackson-core-2.13.2.jar with the same name, the error disappears and the import succeeds  (rename is required because otherwise "file not found" error occurs).

**Comment by cci-faonder** [comment] 2022-08-05 22:16
same issue for me

**Comment by cci-faonder** [comment] 2022-08-05 22:41
when unzip and find the jackson here is the output

 find . -name *jackson*

./m2repo/org/codehaus/jackson
./m2repo/org/codehaus/jackson/jackson-mapper-asl
./m2repo/org/codehaus/jackson/jackson-mapper-asl/1.9.13.redhat-00006/jackson-mapper-asl-1.9.13.redhat-00006.jar
./m2repo/org/codehaus/jackson/jackson-core-asl
./m2repo/org/codehaus/jackson/jackson-core-asl/1.9.13.redhat-00006/jackson-core-asl-1.9.13.redhat-00006.jar
./m2repo/org/codehaus/jackson/jackson-jaxrs
./m2repo/org/codehaus/jackson/jackson-jaxrs/1.9.13.redhat-00006/jackson-jaxrs-1.9.13.redhat-00006.jar
./m2repo/org/codehaus/jackson/jackson-xc
./m2repo/org/codehaus/jackson/jackson-xc/1.9.13.redhat-00006/jackson-xc-1.9.13.redhat-00006.jar
./m2repo/org/jboss/resteasy/resteasy-jackson-provider
./m2repo/org/jboss/resteasy/resteasy-jackson-provider/3.11.2.Final/resteasy-jackson-provider-3.11.2.Final.jar
./m2repo/org/jboss/resteasy/resteasy-jackson2-provider
./m2repo/org/jboss/resteasy/resteasy-jackson2-provider/3.11.2.Final/resteasy-jackson2-provider-3.11.2.Final.jar
./m2repo/com/fasterxml/jackson
./m2repo/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml
./m2repo/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.13.2/jackson-dataformat-yaml-2.13.2.jar
./m2repo/com/fasterxml/jackson/module/jackson-module-jaxb-annotations
./m2repo/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.13.1/jackson-module-jaxb-annotations-2.13.1.jar
./m2repo/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.10.3/jackson-module-jaxb-annotations-2.10.3.jar
./m2repo/com/fasterxml/jackson/datatype/jackson-datatype-jdk8
./m2repo/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.10.3/jackson-datatype-jdk8-2.10.3.jar
./m2repo/com/fasterxml/jackson/datatype/jackson-datatype-jsr310
./m2repo/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.10.3/jackson-datatype-jsr310-2.10.3.jar
./m2repo/com/fasterxml/jackson/core/jackson-databind
./m2repo/com/fasterxml/jackson/core/jackson-databind/2.13.2/jackson-databind-2.13.2.jar
./m2repo/com/fasterxml/jackson/core/jackson-databind/2.10.3/jackson-databind-2.10.3.jar
./m2repo/com/fasterxml/jackson/core/jackson-core
./m2repo/com/fasterxml/jackson/core/jackson-core/2.13.2/jackson-core-2.13.2.jar
./m2repo/com/fasterxml/jackson/core/jackson-core/2.10.3/jackson-core-2.10.3.jar
./m2repo/com/fasterxml/jackson/core/jackson-annotations
./m2repo/com/fasterxml/jackson/core/jackson-annotations/2.13.2/jackson-annotations-2.13.2.jar
./m2repo/com/fasterxml/jackson/core/jackson-annotations/2.10.3/jackson-annotations-2.10.3.jar
./m2repo/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base
./m2repo/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.13.1/jackson-jaxrs-base-2.13.1.jar
./m2repo/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.10.3/jackson-jaxrs-base-2.10.3.jar
./m2repo/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider
./m2repo/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.13.1/jackson-jaxrs-json-provider-2.13.1.jar
./m2repo/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.10.3/jackson-jaxrs-json-provider-2.10.3.jar
./m2repo/com/github/fge/jackson-coreutils
./m2repo/com/github/fge/jackson-coreutils/1.0/jackson-coreutils-1.0.jar

**Comment by EricWittmann** [comment] 2022-08-16 15:54
Right now we have an issue with Thorntail and Jackson.  We're working on it by migrating to Quarkus.  Hoping to have this done and released next week.

See more here:  https://github.com/Apicurio/apicurio-studio/issues/1925

Closing as a duplicate of https://github.com/Apicurio/apicurio-studio/issues/1925

**Closed by EricWittmann** 2022-08-16 15:54 UTC
