### ISSUE TITLE
Introduce the Fabric8 maven plugin to automate the full build/deployment for local development

### ISSUE THREAD

**Issue by danmikita** [Apicurio/apicurio-studio#160] opened 2017-08-15 17:30 UTC
With Apicurio Studio being made up of several pieces now, it may make sense to use [Fabric8](https://maven.fabric8.io/) to create the OpenShift/Kubernetes deployment resources.

**Comment by EricWittmann** [comment] 2017-08-16 10:55
We currently don't really have any support for f8 or kube or openshift.  There is a docker image, which may or may not be useful.  I have an OS v2 cartridge for an Apicurio version of Keycloak (because I'm still waiting for my OSv3 access :)).  Certainly any contributions in the f8/k8s area would be useful.

**Comment by danmikita** [comment] 2017-08-22 13:27
Leading up to innovation days, I'm attempting to complete this story in hopes of lowering the bar of entry to running this guy. I'm looking at the various pieces and parts in regards to how it builds and I'm now at a crossroads of how to proceed.

_First Topic_
**Option 1:** The first option I see is to change from hot deploying a WAR to WildFly to using an embedded Springboot JAR. The reason for this is to simplify how the backend runs. 

**Option 2:** I could use a special Wildfly base container to run the app in its current state as well. 

I would personally find converting to Springboot easier, but I am happy to do either.

_Second Topic_
Organization of the pieces can be done a couple different ways. For the Backend and front end, I would create a separate container for each.

**Option 1:** I could pair them together in a pod. This would make them a 1-to-1 relationship whenever it scales. 

**Option 2:** I create a separate pod for the backend and the frontend so they can scale separately based on load.

@EricWittmann What are your thoughts?

**Comment by EricWittmann** [comment] 2017-08-22 15:45
Some unordered thoughts.  :)

I'd be happy to have support for something non-WildFly (like Spring Boot) but there are some hurdles to consider.  The first is that both WARs use CDI to wire things together.  The second is that they both use Keycloak's WildFly adapter to handle authentication.  Both of these are certainly solvable, but you should be aware of them prior to going down the SB route.

Another option for this topic is to use WildFly swarm.  That is similar to Spring Boot with respect to a simplified runtime, and it already supports at least CDI (not sure about KeyCloak but am guessing it supports that as well). 

Regarding the **Second Topic** - I definitely think the two WARs should be scaled separately.  The back-end will almost certainly require greater scaling than the front-end.  The former needs to handle all of the API calls made by the UI, while the latter really only needs to perform authentication and then serve up some static files (the angular app).

**Comment by danmikita** [comment] 2017-08-22 17:05
Do you have a preference? You called out great points regarding the CDI and Keycloak OpenID dependencies. I researched both just now and feel confident in converting them to SB. 

That being said, this is your project and I don't want to steer it in a direction other than what you want. So - although I would prefer to take it down the SB route, I am more than happy to look into Wildfly swarm if that is what you want.

**Comment by EricWittmann** [comment] 2017-08-22 17:44
Well, I suppose I have a slight "gut" preference to WildFly Swarm over SB.  However that's really only because this is a Red Hat/JBoss project and so is WF Swarm, not because I have any particular experience with the latter (I don't).  That said, we do plenty of Spring Boot stuff around here as well and I believe even certify it in various platforms.

Also note that there is a balance to strike between my steerage of the project and the needs/preferences of its community.  It's a young project so it's mostly me at this point.  :)  But that's not the goal.  The goal is ultimately for the community to grow and contribute an ever larger percentage of the contributions and direction!

So here's what I think.  In general, my main focus with this will be ongoing maintenance.  For example, as new components within the back-end API get introduced, how hard is it to wire them up in both CDI *and* Spring Boot?  If it's trivial to do both, and if we have a reasonable way to test them both, then I'm happy.

Can you give me a preview of what SB support would look like so I have a better idea of the maintenance impact?  (and of course I'm only *assuming* that the impact of supporting WildFly Swarm is low if we're already supporting WF itself)

**Comment by danmikita** [comment] 2017-08-28 17:59
@EricWittmann We have each war running individually right now, but we would like to be able to call the back end api through postman just to test some stuff. We are having problems figuring out how to get a token. When we visit /api-hub we get an error message "Bearer-only applications are not allowed to initiate browser login". Do you have any tips for us to get it so we can call the backend directly?

**Comment by EricWittmann** [comment] 2017-08-28 18:29
You need to obtain an access token from the Keycloak server.  Try this:

```
curl --data "grant_type=password&client_id=apicurio-ui-dev&username=USER&password=PASSWORD" https://auth-apistudio.rhcloud.com/auth/realms/apicurio-local/protocol/openid-connect/token
```

The response should be a JSON payload with an access token.  You should be able to send that access token via the HTTP Requests's Authentication header IIRC:

```
bearer ACCESS_TOKEN_FROM_JSON
```

I'll confirm locally...

**Comment by EricWittmann** [comment] 2017-08-28 18:38
I've confirmed locally using Postman and the 0.1.9 quickstart version of apicurio studio.  I used the above curl command to fetch an access code and then used that in a Postman request to my localhost version of Apicurio Studio.  Success!

The value of the **Authorization** header I used for my postman request was:

```
bearer ACCESS_TOKEN
```

**Comment by danmikita** [comment] 2017-08-28 18:45
I'm hoping this isn't a stupid question... What is the USER and PASSWORD supposed to be? We can't find it in any configuration file...

**Comment by EricWittmann** [comment] 2017-08-28 18:55
The credentials you would use to login to Apicurio Studio via the login screen in the UI.  Now, if you're using your Google account to log in, then that's problematic.  Fortunately I may have another solution that I just researched. :)

Since Postman has support for OAuth2, I tweaked some config on the Keycloak server to allow the Postman client to authenticate.  Here's how you should configure Postman:

1. In the **Authorization** tab for your Postman Request, choose "OAuth 2.0" as the **Type**

![image](https://user-images.githubusercontent.com/1890703/29788318-238d46ac-8c00-11e7-8145-cef7006850b1.png)

2. Click that **Get New Access Token** button.
3. Fill out the resulting dialog (see values below)

![image](https://user-images.githubusercontent.com/1890703/29788351-3e39e212-8c00-11e7-97e6-b100903f6cb5.png)

VALUES:
**Auth URL**
```
https://auth-apistudio.rhcloud.com/auth/realms/apicurio-local/protocol/openid-connect/auth?redirect_uri=https://www.getpostman.com/oauth2/callback&response_type=code&client_id=apicurio-ui-dev
```
**Access Token URL**
```
https://auth-apistudio.rhcloud.com/auth/realms/apicurio-local/protocol/openid-connect/token
```
**Client ID**
```
apicurio-ui-dev
```
**Grant Type**
```
Authorization Code
```

4. Click **Request Token**
5. You should then be prompted to login with a popup UI page
6. The result should be an entry in the **Existing Tokens** list

![image](https://user-images.githubusercontent.com/1890703/29788507-decc4ae4-8c00-11e7-9aa4-a1a0d78f66a8.png)

7. Click the **Use Token** button and it will add the token to the Request
8. Profit!

**Comment by EricWittmann** [comment] 2017-08-28 18:55
I should probably write a blog post or something on this. :)

**Comment by EricWittmann** [comment] 2017-08-28 18:58
BTW when you click the **Use Token** button it will basically just add a **Authorization** header to the request.  This is the same thing that would happen using the Curl method above, but without all the manual copying and pasting of stuff *AND* presumably with support for using your Google account to login...

**Comment by danmikita** [comment] 2017-08-28 19:25
AWESOME! This worked! Thank you! As a quick update for you - We have implemented Wildfly Swarm for the back-end and the front-end and we have it running locally in a container on Kubernetes with Fabric8. We are still dealing with some H2 datasource configurations and pod coordination, but we are VERY close with this one.

Two other groups have been working on Bitbucket and Gitlab respectively, but were getting tripped up on the Keycloak stuff due to needing to set up the Keycloak Identity Provider. Thus - we got a Keycloak server running for our team to work with for now. Would it make sense to put Keycloak in a container to run along side the rest of the app?

Hopefully tomorrow we can get more code written. Thank you again for your help today!

**Comment by EricWittmann** [comment] 2017-08-28 21:40
Trying to reply via email.  Hopefully this works!

I think spinning up a keycloak pod would be ideal but I have no idea how
hard it is to bootstrap it with all the right configuration.  Which is why
the quickstart uses the cloud version. 😀

**Comment by danmikita** [comment] 2017-08-30 16:52
OK - at the end of yesterday we have the backend working perfectly as a standalone container. It also deploys automatically using Fabric8 with a simple ```mvn clean install```. 

As for the front-end, we got it deploying with Fabric8 and got it fairly close, but we are still running into some issues connecting it to the backend. We simply ran out of time yesterday to finish. I plan on finishing this up by the end of next week.

My expected end result is:

- Backend container
- Frontend container
- Postgres Container with persistent storage
- Keycloak container with auto configuration

Ultimately this would do away with the whole quickstart concept...although it does/will still work. There will probably need to be some decisions made about if there should be some clean up of code when this is all done.

**Comment by EricWittmann** [comment] 2017-08-30 17:41
Sounds good - I look forward to seeing how everything is structured!

**Comment by danmikita** [comment] 2017-09-10 01:24
@EricWittmann We need your help... If you have time, we are need help understanding the routing in Angular. This is current state:

> Running `mvn clean install` will build a back-end Wildfly Swarm container as well as a front-end Wildfly Swarm container using Fabric8. Fabric8 also takes care of deploying them to Minikube and exposes them by creating Services within K8 for them. _(Disclaimer: We are pointing to our own Keycloak instance right now because each time the Service is created and exposed in Minikube it receives a new port, which we need to manually add to Keycloak each time. This will be addressed once we know the app is converted properly.)_ As far as we can tell - it all works. 

What isn't working is some of the pages. Specifically the Linked Accounts page: `/studio/settings/accounts`. The logs don't show any errors, and neither I or @mccrackend know Angular well enough to figure this out. Do you have any pointers for us? I'd really like to seal this PR up for everyone.

**Comment by EricWittmann** [comment] 2017-09-10 01:59
In what way is the Linked Accounts page not working?  Blank page?  Error of some sort?

There is a fair amount of UI logging information in the javascript console - anything interesting there?

**Comment by danmikita** [comment] 2017-09-10 02:03
HA! Thank you! Like I said, we aren't front end guys so we didn't even think to check that.... I found the problem, looks like a 404 to the backend call. 👍 I'm off to the races now.

**Comment by EricWittmann** [comment] 2017-09-10 02:10
Great!  Wish I had a REST based set of unit tests that you could run against the back-end, but the existing tests currently instantiate the jax-rs objects and invoke them directly to avoid spinning up a whole tomcat or wildfly instance.  Maybe I should re-think that decision...

**Comment by danmikita** [comment] 2017-09-11 15:58
Getting closer - just dealing with some routing issues now. Because we separated the front-end from the back-end I need to create a reverse proxy in Undertow to route the traffic appropriately from the front-end container to the back-end container. Then just a little code cleanup. I think I'll do the keycloak in a container in a separate issue.

**Comment by danmikita** [comment] 2017-09-13 16:21
@EricWittmann Can you add:

- http://192.168.99.100:32201/*
- http://192.168.99.100:32202/*

To the Valid Redirect URIs in Keycloak?

**Comment by EricWittmann** [comment] 2017-09-13 19:08
Yes, which realm are you using?  Options are:

* apicurio
* apicurio-local

**Comment by danmikita** [comment] 2017-09-13 19:18
We are currently using **apicurio-local**.

PSA - we are done. I just want to update the README with some new instructions and squash our commits into more logical units. We will do that tomorrow over lunch. There are definitely some other things I want to do as follow up stories to this:

- Create constants/configs for all the strings sprinkled throughout the java classes
  - This may be able to use the K8s config map and secrets features
- Configure K8s to use a persistent volume for the backend H2 database
- Possibly remove/clean up some legacy files. (This all depends on if you like what we did. 😨 )
- Add a local Keycloak container that auto-configures.

I have had multiple people pull this down and run it with a single command - so it has been tested. 😄  I haven't made sure the quickstart still works though. I'd like you to try this new set-up and weigh in on whether we should support both configurations or not.

Anyway - you'll see all the goodies tomorrow! If you're curious you can always check it out on my [branch](https://github.com/danmikita/apicurio-studio/tree/feature/wildfly_swarm).

**Comment by EricWittmann** [comment] 2017-09-13 19:48
OK I've added those two endpoints to the valid redirect URLs for the client.  Give it a try and let me know.

This is obviously a short-term fix until you get a local Keycloak container working (I presume).  :)

**Comment by EricWittmann** [comment] 2019-04-18 17:12
I suspect this issue is now well out of date.  Closing it.  But please re-open if I'm wrong.

**Closed by EricWittmann** 2019-04-18 17:12 UTC
Labels: task, wontfix
