### ISSUE TITLE
can we create reuseable examples..? if yes how..?

### ISSUE THREAD

**Issue by Brijesh-briju** [Apicurio/apicurio-studio#1106] opened 2020-04-03 12:26 UTC
can we create reuseable examples..? if yes how..?

**Comment by bodograumann** [comment] 2021-05-18 06:19
I think this is a duplicate of #240

**Comment by EricWittmann** [comment] 2021-05-20 20:13
Yes it is!  Thanks for linking it.  Closing this in favor of #240.

**Closed by EricWittmann** 2021-05-20 20:13 UTC
Labels: enhancement, question
