### ISSUE TITLE
CORS policy issue after Quarkus update

### ISSUE THREAD

**Issue by v-bilous** [Apicurio/apicurio-studio#2130] opened 2023-03-11 17:49 UTC
Hi @EricWittmann , how r u?

I see an issue related to the new version of Quarkus.
It's probably the new behavior for CORS settings.
When we have 
`quarkus.http.cors=true` only set
I see the same issue when I open UI  https://github.com/quarkusio/quarkus/issues/31523
<img width="1579" alt="Screenshot 2023-03-11 at 19 48 42" src="https://user-images.githubusercontent.com/19833841/224503883-fe777286-a09c-459c-bed3-ec598792512d.png">

`quarkus.http.cors.origins=*` is fix the issue for me.

Thanks,
Vova

**Comment by adel-chouchane** [comment] 2023-03-14 09:17
Hello @v-bilous , I am using the latest images of apicurio and i am having the same error, what is the env variable i need to pass to the UI ?

**Comment by v-bilous** [comment] 2023-03-14 09:37
hi @adel-chouchane , thank you! you are right, what I see it should be fixed in `apicurio-studio-ui`, but CORS rules were added to `apicurio-studio-api` only.
The change https://github.com/Apicurio/apicurio-studio/commit/9d94555a7a364e973e4a99fae6219d05cc246d80

@adel-chouchane you can take this image which is based on the latest version as a temporal solution `djetcloud/apicurio-studio-ui:1.0.3`, or just use the previous version `apicurio/apicurio-studio-ui:0.2.59.Final`

**Comment by EricWittmann** [comment] 2023-03-15 11:04
Hey everyone.  I don't think the UI project should need the CORS changes.  CORS enablement **should** only be needed on the REST API, not on the UI project.

I think my changes have fixed studio.apicur.io, and everything works locally for me now.  Please correct me if I"m wrong!

There is a new release 0.2.61.Final that you can try and let me know what happens.

**Comment by EricWittmann** [comment] 2023-03-15 15:34
This has been confirmed - it was working ok in Firefox but failing in Chrome and Safari.  I've merged the PR and I have a fix for the issue (env var config) ready for deployment in studio.apicur.io.  Once the ops team has a chance to merge that PR we should be good.  I'll close this as fixed and we can re-open it if it's still failing.

**Comment by EricWittmann** [comment] 2023-03-15 15:35
Thanks @v-bilous for the PR.

**Closed by EricWittmann** 2023-03-15 15:34 UTC

**Comment by v-bilous** [comment] 2023-03-16 16:51
Thank you for resolving it @EricWittmann

**Comment by EricWittmann** [comment] 2023-03-22 11:04
The 0.2.59 version still has the issue - can you try 0.2.61 instead?  If that doesn't work can you provide a little more information about exactly what is happening?

**Comment by v-bilous** [comment] 2023-03-22 16:49
Hey @adel-chouchane ,

Nice 2 meet you. Could you share your context to us. What is the local gitlab instance? Where it's installed? How you integrate? How do you deploy Apicurio images and what the use case scenario when you face this issue? 
It would be helpful if you add some screenshots, stacktrace, your configuration. 

BR,
Vova

**Comment by adel-chouchane** [comment] 2023-03-23 07:31
Hello @v-bilous, 
I am using the 0.2.61.Final versions of the 3 components.
The dashboard works totaly fine, i can check my APIs and can create and edit new ones.
The only problem i have is when trying to link my apicurio account to a gitlab account.

- the gitlab instance is installed in a remote server, I am linking it to apicurio api via this env var : APICURIO_GITLAB_API_URL
- For the images deployment i made a custom helm but it's mainly based on the env vars defined in distro/docker-compose deployment
- To reproduce the issue: 1) login to apicurio 2) go to linked accounts 3) try to link a gitlab account

ScreenShots:
![Success Get on /accounts ](https://imgur.com/xHgZJ1m)
![500 response POST on /accounts when trying to link to gitlab](https://imgur.com/H2oCwS0)
![Log from the UI console](https://imgur.com/L2d4OF7)
![the UI you get](https://imgur.com/LIODmkG)

Error stacktrace that appears on the api container: 
2023-03-23 07:07:47,299 ERROR [io.und.req.io] (executor-thread-0) Exception handling request 09d97979-a0f8-4a5c-bba8-6625e31ff50a-1 to /accounts: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalStateException
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
        at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:35)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.apicurio.hub.api.security.QuarkusAuthenticationFilter.doFilter(QuarkusAuthenticationFilter.java:83)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.apicurio.hub.api.filters.DisableCachingFilter.doFilter(DisableCachingFilter.java:66)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.apicurio.hub.api.filters.CorsFilter.doFilter(CorsFilter.java:64)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:602)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:120)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:417)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException
        at io.apicurio.hub.api.security.QuarkusLinkedAccountsProvider.initiateLinkedAccount(QuarkusLinkedAccountsProvider.java:132)
        at io.apicurio.hub.api.security.QuarkusLinkedAccountsProvider_ClientProxy.initiateLinkedAccount(Unknown Source)
        at io.apicurio.hub.api.rest.impl.AccountsResource.createLinkedAccount(AccountsResource.java:135)
        at io.apicurio.hub.api.rest.impl.AccountsResource_ClientProxy.createLinkedAccount(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 59 more
