### ISSUE TITLE
AsyncAPI: Editing a channel in source editor causes a circular reference

### ISSUE THREAD

**Issue by GoulvenF** [Apicurio/apicurio-studio#1626] opened 2021-08-12 08:09 UTC
Hi,

We got trouble when editing an AsyncAPI channel from the source view. The save button triggered a circular reference issue, as below: 

![image](https://user-images.githubusercontent.com/71071559/129161301-e5c09440-b3d4-473b-acb4-f607bff6261d.png)

Thanks,

**Comment by EricWittmann** [comment] 2021-08-20 14:51
This should be resolved by https://github.com/Apicurio/apicurio-data-models/pull/309

**Comment by GoulvenF** [comment] 2021-08-23 14:54
Hi,

Thanks. We would need to have the 1.1.14 used in the studio, in order to complete the bugfix. Could you re-open ?

Best regards,

**Comment by EricWittmann** [comment] 2021-08-23 17:12
OK I've upgraded apicurio-data-models to 1.1.14 in both `pom.xml` and `package.json`.  Is there more to fixing this than that?

**Comment by DyspC** [comment] 2021-08-23 18:55
An add command is created [right there](https://github.com/Apicurio/apicurio-studio/blob/master/front-end/studio/src/app/pages/apis/%7BapiId%7D/editor/_components/forms/channel-form.component.ts#L73) instead of a replace.

I was working on this (+ implementing cloneChannel) but I started encountering those errors https://github.com/Apicurio/apicurio-studio/runs/3402960785#step:4:21009

I don't really see anything [between 1.1.13 and 1.1.14](https://github.com/Apicurio/apicurio-data-models/compare/1.1.13...1.1.14), perhaps a regression following the jsweet upgrade?

**Comment by EricWittmann** [comment] 2021-08-23 19:09
I believe I have fixed the errors you linked to above.  The workflow is still in progress so we'll know as soon as that's done.  But my fix worked locally.

**Comment by DyspC** [comment] 2021-08-24 18:23
I think there are still some runtime issues following the update, something crashes in the js bundle when I try to access the dashboard and it looks like Oas30PathItem is undefined when it needs to be extended

![image](https://user-images.githubusercontent.com/17125930/130668511-dc93ead1-1143-4cd9-b04d-4b127b11e8bb.png)

---

89556eff82a3e9894f3672f07959e6e2d871db15
![image](https://user-images.githubusercontent.com/17125930/130669620-195b86f6-9962-423a-b981-d5bb3979f161.png)

3eac2b5c
![image](https://user-images.githubusercontent.com/17125930/130668468-eae6150a-fa1e-45b4-9355-4cb874c3b96e.png)

**Comment by EricWittmann** [comment] 2021-08-24 18:33
OK I'll need to dig into this - it could be a JSweet regression.  Not sure...

**Closed** 2021-08-30 12:41 UTC
Labels: bug
