### ISSUE TITLE
Unable To Link Github With Apicurio

### ISSUE THREAD

**Issue by Surbhi27946** [Apicurio/apicurio-studio#1345] opened 2020-12-08 05:25 UTC
Hi,
I followed : https://www.apicur.io/studio/docs/setting-up-keycloak-for-use-with-apicurio in order to have our Github as an identity provider with APicurio running locally in our system.

We can see the login option with github is there  :
<img width="1788" alt="Screenshot 2020-12-08 at 10 53 33 AM" src="https://user-images.githubusercontent.com/73223705/101443572-be1b8a00-3943-11eb-9725-e914577bed01.png">

But on clicking the Github login option, We are getting redirected here :
<img width="1779" alt="Screenshot 2020-12-08 at 10 55 14 AM" src="https://user-images.githubusercontent.com/73223705/101443610-dc818580-3943-11eb-8541-dd8d7e5941f2.png">

Can you please help on what might have gone wrong?

**Comment by Surbhi27946** [comment] 2020-12-08 05:31
This is the oauth application that I registered in our github :
![Uploading Screenshot 2020-12-08 at 10.57.50 AM.png…]()

**Comment by Surbhi27946** [comment] 2020-12-08 07:01
Also, this github is internal of our organisation : https://gecgithub01.walmart.com/
But on logging in, I am getting directed to my personal github page.

**Comment by EricWittmann** [comment] 2020-12-08 12:48
The screenshot for the OAuth application didn't come through.  I can't tell from the 404 github page what might be wrong.  However, Keycloak has some additional documentation on this here:

https://www.keycloak.org/docs/latest/server_admin/index.html#github

Have a look at that and see if it helps.  Without more information (e.g. screenshots of the actual configuration params in Keycloak and Github) I can't be of more help. :(

**Comment by Surbhi27946** [comment] 2020-12-08 13:51
Sorry for that.
Here is the screenshot for the application that we created in our gecgithub :

<img width="1605" alt="Screenshot 2020-12-08 at 10 57 50 AM" src="https://user-images.githubusercontent.com/73223705/101491642-0067ba00-398a-11eb-8d72-d4681d7ea75e.png">

And the keycloak configuration for the identity provider is:
<img width="1758" alt="Screenshot 2020-12-08 at 7 19 31 PM" src="https://user-images.githubusercontent.com/73223705/101491916-50468100-398a-11eb-8200-80dbf5e5185f.png">

Is it possible that it is happening because I am configuring github as identoty provider on keycloak, whereas the client and the secrets belong to the oauth application created on gecgithub?

**Comment by EricWittmann** [comment] 2020-12-08 14:18
Ah ha!  I didn't put that together initially.  You are trying to integrate with an instance of GitHub Enterprise, not with github.com.  I thought you were referring to a private organization on github.com.  My mistake.

So yeah - you will need some different configuration.  Instead of configuring a **github.com** identity provider in Keycloak, you will need to configure a **OpenID Connect v1.0** identity provider instead.  The good news is that I'm confident this is possible to do without much trouble.  The bad news is that I don't have this specific use-case documented, because I don't have access to a GitHub Enterprise installation that I can use to test and verify the configuration steps.

We **do** have documentation on how to configure a local Git**Lab** server, which is exactly what you want to do but with GitHub Enterprise instead of GitLab CE.  Here is the GitLab article for reference:

https://www.apicur.io/studio/docs/using-a-local-installation-of-gitlab

You could try to adapt the information in that article for your situation.

To make this even more complicated (I hope I'm not scaring you away), there is an issue with using the Keycloak OpenID Connect identity provider type with GitHub Enterprise.  The problem is discussed here:  https://github.com/Apicurio/apicurio-studio/issues/831

We have a solution to that problem in the form of a custom Keycloak extension that provides a configurable version of the standard GitHub Keycloak social connector.  You can find that extension (with Readme documentation) here:

https://github.com/Apicurio/apicurio-keycloak-extensions

Ignore the GitLab section of the readme and focus on the GitHub section. 👍

**Comment by Surbhi27946** [comment] 2020-12-08 17:20
@EricWittmann 
I went through the documentation you provided : https://www.apicur.io/studio/docs/using-a-local-installation-of-gitlab

Sorry but I have few basic questions :
1) I am using the quickstart to set up the Apicurio locally in my system.
So where exactly these environment need to be set ?
APICURIO_GITLAB_API_URL="https://gitlab.example.com"
export APICURIO_GITLAB_API_URL 
2) What exactly is the environment variable that I should set - APICURIO_GITHUB_API_URL ?

**Comment by EricWittmann** [comment] 2020-12-08 17:45
For GitHub there are two environment variables you must set (or you can use system properties).  These are:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-core/src/main/java/io/apicurio/hub/core/config/HubConfiguration.java#L46-L50
![image](https://user-images.githubusercontent.com/1890703/101520511-9b44a200-3952-11eb-9d9f-f76f5605650e.png)

You can **either** use the environment variable approach **or** the system property approach.  If using env vars, something like this:

```
export APICURIO_GITHUB_URL=https://mygithub.example.com
export APICURIO_GITHUB_API_URL=https://api.mygithub.example.com
$STUDIO_HOME/bin/standalone.sh -b 0.0.0.0 -c standalone-apicurio.xml
```

If you want to use system properties you can either add them to the right place in the `standalone-apicurio.xml` file found in the quickstart (in `standalone/configuration`) or you can add them to the command line:

```
$STUDIO_HOME/bin/standalone.sh -Dapicurio.hub.github.url=https://mygithub.example.com -Dapicurio.hub.github.api=https://api.mygithub.example.com -b 0.0.0.0 -c standalone-apicurio.xml
```

**Comment by EricWittmann** [comment] 2020-12-08 17:47
I realize you're just trying to get this working (step 1) but I wanted to mention that it's not recommended to use the Quickstart in production.  That's intended to be an evaluation deployment (get started fast).  If your plan is to run something in production, I would strongly suggest doing so using the docker images (either via docker compose, kubernetes, or OpenShift).

**Comment by Surbhi27946** [comment] 2020-12-08 18:28
Okay. Thanks a lot @EricWittmann 
Will try this up.

**Comment by Surbhi27946** [comment] 2020-12-09 10:45
@EricWittmann 
I tried the steps you suggested. I even cloned and build the https://github.com/Apicurio/apicurio-keycloak-extensions and then put the jar in the keycloak standalone/deployments directory as given in the Readme.

And then i am using this command to start my local keycloak instance :
**./bin/standalone.sh -Dapicurio.hub.github.baseUrl=https://gecgithub01.walmart.com -Dapicurio.hub.github.apiUrl=https://gecgithub01.walmart.com/api/v3**

But still the GitHub Enterprise is not getting listed in the Identity providers dropdown.
<img width="1786" alt="Screenshot 2020-12-09 at 4 12 37 PM" src="https://user-images.githubusercontent.com/73223705/101619757-b63e1180-3a39-11eb-8a35-965d6a988929.png">

**Comment by Surbhi27946** [comment] 2020-12-09 16:23
Do I need to take some other action as well?

**Comment by EricWittmann** [comment] 2020-12-09 19:42
What version of Keycloak are you using?  I'll try to reproduce.

**Comment by EricWittmann** [comment] 2020-12-09 19:43
Note: it's possible that you don't have GitHub in that list because you already have a GitHub social connector created.  Maybe try deleting that one and seeing if the dropdown changes?  I think this because I don't see **either** "GitHub" entry in the list.  And they both have the same built-in value for "provider id" of `github`.

**Comment by Surbhi27946** [comment] 2020-12-10 09:52
@EricWittmann 
Indeed the issue was that I already had github social connector create.
It got resolved after deleting it.
Things are working fine, except out of some 10 logins, 1 login is giving "Bad Request".
The logs are not saying anything on Apicurio or Keycloak server.
I am trying to figure out why it is happening.

Also everytime, we are logging out, we can see these logs on the Apicurio :

14:38:33,454 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) state parameter invalid
14:38:33,476 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) cookie: 0d7b2d99-75a7-403a-979c-6dc9cc8ee9ae
14:38:33,476 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) queryParam: 7205f3ed-9881-470c-b56f-c8f993ddf35c
14:38:36,933 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) state parameter invalid
14:38:36,933 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) cookie: 0d7b2d99-75a7-403a-979c-6dc9cc8ee9ae
14:38:36,933 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) queryParam: 7205f3ed-9881-470c-b56f-c8f993ddf35c
14:38:41,366 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) state parameter invalid
14:38:41,367 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) cookie: 0d7b2d99-75a7-403a-979c-6dc9cc8ee9ae
14:38:41,367 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) queryParam: 7205f3ed-9881-470c-b56f-c8f993ddf35c
14:38:43,340 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) state parameter invalid
14:38:43,340 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) cookie: 0d7b2d99-75a7-403a-979c-6dc9cc8ee9ae
14:38:43,340 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-30) queryParam: 7205f3ed-9881-470c-b56f-c8f993ddf35c
15:12:52,971 ERROR [io.undertow.request] (default task-31) UT005023: Exception handling request to /studio/logout: java.lang.NullPointerException
	at io.apicurio.studio.fe.servlet.filters.BaseHrefFilter.doFilter(BaseHrefFilter.java:62)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.studio.fe.servlet.filters.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:81)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.studio.fe.servlet.filters.ResourceCacheControlFilter.doFilter(ResourceCacheControlFilter.java:81)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)

15:13:06,416 ERROR [io.undertow.request] (default task-31) UT005023: Exception handling request to /studio/logout: java.lang.NullPointerException
	at io.apicurio.studio.fe.servlet.filters.BaseHrefFilter.doFilter(BaseHrefFilter.java:62)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.studio.fe.servlet.filters.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:81)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.studio.fe.servlet.filters.ResourceCacheControlFilter.doFilter(ResourceCacheControlFilter.java:81)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Surbhi27946** [comment] 2020-12-14 07:15
@EricWittmann 
Indeed the issue got resolved after deleting the github identity provider.
Now I can see the Github enterprise entry in the drop down.
Thanks a lot for you your help and support.

**Comment by EricWittmann** [comment] 2020-12-16 20:12
OK great!  It sounds like you have things going OK.  I'm going to close this for now but please feel free to re-open it if you need additional support.

Also if you get everything working the way you want, please consider contributing documentation for how to configure Studio with GitHub Enterprise.  It would be **very** appreciated!  :)

**Closed by EricWittmann** 2020-12-16 20:12 UTC
Labels: question

**Comment by Surbhi27946** [comment] 2020-12-17 05:11
Surely I would be glad to contribute in the documentation for github enterprise as we have things working as expected.
Let me know the space where can I start documenting or the procedure for it.
Thanks

**Comment by EricWittmann** [comment] 2020-12-17 15:22
That would be amazing, thanks!  The Studio documentation is located here:

https://github.com/Apicurio/apicurio.github.io/tree/master/_pages/studio/docs

I would suggest making a copy of `using-a-local-installation-of-gitlab.md` and using it as a template for a GitHub specific version of it.  :)

**Comment by Surbhi27946** [comment] 2020-12-17 18:23
@EricWittmann 
I have created the documentation.
Let me know how can I push it into the source code or how can i raise the PR for it.
Thanks

**Comment by EricWittmann** [comment] 2020-12-18 15:05
That's great!  If you wanted to fork that repository and then submit a PR that would be great.  If you want to attach the file to this issue or email it to me, that's fine too (my email address is in my GitHub profile).

**Comment by Surbhi27946** [comment] 2020-12-22 08:04
Hi @EricWittmann 
Raised the PR https://github.com/Apicurio/apicurio.github.io/pull/11
Thanks

**Comment by EricWittmann** [comment] 2020-12-22 14:17
Fantastic, thanks so much!
