### ISSUE TITLE
Unable to save api in source mode in v02.57-final

### ISSUE THREAD

**Issue by danylaberge** [Apicurio/apicurio-studio#1992] opened 2022-08-24 13:13 UTC
Good day, this issue started with the release of 0.2.55-final and is still currently doing it. Steps leading to issue : 

1. Open and edit an API design
2. Go to source tab where you can see the full api source code
3. Do a change
4. Save changes
5. An error will occur
![image](https://user-images.githubusercontent.com/21954900/186427090-c180e11c-b4ec-45c2-aa77-a1e695b01ab0.png)

- Happens only in source of full api specifications
- doesn't happen in design mode
- doesn't happen in source mode when in individual path or components

We are running out of azure openshift and the application has been redeployed this morning with 0.2.57-final.

Thanks

**Comment by EricWittmann** [comment] 2022-08-25 19:29
Wow this is a strange one!  I've not seen anything like this before.  The Lost Connection warning would typically only happen if the websocket between the browser and editing server is broken.  

Some questions:

* Do you see any server logs in the apicurio-studio-ws component?
* How big are your API definitions?  If they are large can you try to reproduce this with a small (hello world) definition?

My best guess is some sort of web socket message size limit is being hit.

**Comment by danylaberge** [comment] 2022-08-25 20:17
I found the following in the ws logs

2022-08-25 20:05:36,377 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3034 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked

2022-08-25 20:05:53,578 INFO  [io.api.hub.cor.cmd.OaiCommandExecutor] (vert.x-eventloop-thread-1) Applying 2 commands to a document.
|INFO| [ChangeDescriptionCommand] Executing.
|INFO| [AbstractReplaceNodeCommand] Executing.
2022-08-25 20:05:55,580 WARN  [io.net.cha.DefaultChannelPipeline] (vert.x-eventloop-thread-1) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.

- Yes, the API Specs are fairly large, mostly only schema definitions with a lot of external refs
- Doesn't seem to have an issue with small specs
- Reconnect doesn't work, changes will be lost when navigating out.

**Comment by EricWittmann** [comment] 2022-08-26 13:35
Interesting!  I think `Max frame length of 65536 has been exceeded.` may be confirmation of the "too large API spec" theory.  I'll need to do some sleuthing on this.  The likely root cause / reason is our switch from Thorntail to Quarkus as the basis for the Docker images.  I'm guessing there is a Quarkus configuration property for max frame size in a web socket.

**Comment by EricWittmann** [comment] 2022-08-26 13:40
Confirmed:  https://quarkus.io/guides/all-config#quarkus-websockets-client_quarkus.websocket.max-frame-size

So the good news is that you **may** be able to modify this without any need for a new release.  Try setting the following environment variable for the `apicurio-studio-ws` pod:

`QUARKUS_WEBSOCKET_MAX_FRAME_SIZE`

Set it to the number of bytes you think exceeds the max size of your APIs.

**Comment by danylaberge** [comment] 2022-08-26 14:49
Added this to the environment variable : 

        - name: QUARKUS_WEBSOCKET_MAX_FRAME_SIZE
          value: '131072'

Still got the error
io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:424)

Maybe not formatted properly. I tried as a number 131_072 but was expecting a string

**Comment by EricWittmann** [comment] 2022-08-26 15:38
Rats.  And you definitely added it to the `-ws` pod (not the `-api` pod)?

I'll need to try to reproduce locally...

**Comment by danylaberge** [comment] 2022-08-26 15:50
Yeah, I confirm in the -ws

![image](https://user-images.githubusercontent.com/21954900/186943693-5d7d505f-8b5f-4a6e-a32b-7095a0fe9f8d.png)

**Comment by danylaberge** [comment] 2022-08-26 15:58
The API spec is currently sitting at 40kb in file size

**Comment by EricWittmann** [comment] 2022-08-26 16:04
OK thanks.  We'll have to dig into it more.  @carlesarnal is our docker compose config working?

**Comment by carlesarnal** [comment] 2022-08-26 16:31
Hi all, sorry for being late to the party. Changing the env var in the pod is not going to make a difference since that property is a build time property (the value is fixed at build time), notice the lock in the quarkus documentation next to the property name. The only thing we can do I'm afraid to address issues like this one is to release a new version with a higher value for that property.

@EricWittmann, yes, the docker-compose distro works.

**Comment by EricWittmann** [comment] 2022-08-26 17:56
Thanks @carlesarnal !  My mistake.   I didn't realize it was a build time property.  So we'll need to make a change on our end for this.

**Comment by EricWittmann** [comment] 2022-08-29 16:24
OK @danylaberge I've committed this change:

https://github.com/Apicurio/apicurio-studio/commit/3f2a21360522ce4869f7f3d3c407b9eebd243fe8

Are you able to build and test in your environment or would you require a new release to do that?

**Comment by danylaberge** [comment] 2022-08-29 19:06
Sorry we are able to do builds at the moment, we will need a new release. What is the value you plan to set it?

**Comment by EricWittmann** [comment] 2022-08-29 20:58
I have it set to 2MB for the production profile.

**Comment by uri-nevvon** [comment] 2022-12-16 18:01
I'm getting the same in the "Studio" hosted version which I use a lot. Is there a workaround I can use? my only option is to copy the YML and start a new API, but that's a pain

**Comment by EricWittmann** [comment] 2022-12-20 16:55
Apologies - I thought this was fixed in the hosted version, but we realized today that we never pushed the fix.  :(  That will be done soon.  I've done a new release of Studio and we'll get that new release deployed to studio.apicur.io as soon as the ops people allow.  Since it's the end of the year, it may or may not happen this week.  Because the evaluation (hosted) version of Apicurio Studio is non-production, that may either result in it actually getting deployed sooner (because real production apps are frozen) or later (priority given to end of year releases of production apps).  We'll see how it goes!!

**Closed by EricWittmann** 2022-12-20 16:55 UTC
Labels: task, component/studio, priority/normal

**Comment by EricWittmann** [comment] 2022-12-21 14:10
`0.2.59.Final` has been released and deployed to studio.apicur.io

Please re-open this if you still have the source tab problem!

**Comment by berlinger-ciprianpetrisor** [comment] 2023-03-27 11:15
@EricWittmann 

I'm using 0.2.59.Final and am still running into this issue:
![image](https://user-images.githubusercontent.com/95405175/227926100-6044f1d5-e228-4d4c-93f2-cf20f183126e.png)


Looking at the config file edited in https://github.com/Apicurio/apicurio-studio/commit/3f2a21360522ce4869f7f3d3c407b9eebd243fe8, I see there's also a 'mysql' profile at the bottom.

Does that need to also specify the ```%mysql.quarkus.websocket.max.frame.size=2097152``` in order for this to work, or am I confusing the issue entirely?

**Comment by EricWittmann** [comment] 2023-03-27 13:15
Quarkus can have multiple profiles enabled at the same time, so it should **not** be necessary to add the same property to the msyql profile.

The reason it's not working for you is that I think I got the name of the property wrong when I fixed this initially for 0.2.59.  It's been fixed since then here:

https://github.com/Apicurio/apicurio-studio/pull/2124

So if you upgrade to 60 or 61 it should work.  Sorry for the inconvenience.

**Comment by berlinger-ciprianpetrisor** [comment] 2023-03-29 06:32
@EricWittmann 

I have upgraded to 0.2.61 (all components) and configured CORS as you instructed in the other thread.
APICurio now works also in Chrome and Edge, however I am still running into this issue on 61:
![image](https://user-images.githubusercontent.com/95405175/228445376-87f31716-6f0f-4618-9933-91c19b0d781c.png)

All I'm doing is editing the 'description' field on an API from the Source tab.
The entire API definition is  ~ 4000 lines or 175k characters, which is not that large.
Is there any option on the websocket service I can configure that raises the limit above 65536 ?
