### ISSUE TITLE
apicurio-ws does not output some config information to the log even though the log level is DEBUG

### ISSUE THREAD

**Issue by Yuutakasan** [Apicurio/apicurio-studio#969] opened 2019-11-09 18:24 UTC
apicurio-ws does not output some config information to the log even though the log level is DEBUG

APICURIO_SHARE_FOR_EVERYONE variable is not output as a log in container log of apicurio-studio-ws.

https://github.com/Apicurio/apicurio-studio/issues/954#issuecomment-552110580

**Comment by EricWittmann** [comment] 2020-02-11 11:09
I was not able to reproduce this locally.  :(  The log information seems complete when I run either locally or in Docker/docker-compose.  Marking as closed, but please feel free to reopen this if you can find reliable steps to reproduce.

**Closed by EricWittmann** 2020-02-11 11:09 UTC
