### ISSUE TITLE
Publishing Spec to Github fails

### ISSUE THREAD

**Issue by lhuria94** [Apicurio/apicurio-studio#1945] opened 2022-07-06 06:01 UTC
Hi Team,

Thanks for the amazing tool.
We are trying to publish the spec manually via APIcurio "Publish" action.
![Screenshot 2022-07-06 at 11 28 05 AM](https://user-images.githubusercontent.com/10358379/177479351-63f9d23d-b90b-4492-8592-7ce976b05b8e.png)

Although being able to link GitHub account successfully, but click on publishing always throw an error:
![Screenshot-2022-06-29-at-4-10-01-PM-png-1123×316-](https://user-images.githubusercontent.com/10358379/177479482-c3b3bf74-1337-4dea-bfce-ab910e7dc4ca.png)

Does this work in a different way?
Also, wanted to check if there is a way to automate it.

**Comment by EricWittmann** [comment] 2022-07-08 17:16
Nevermind, I just tried this on https://studio.apicur.io and was able to reproduce your same issue:

![image](https://user-images.githubusercontent.com/1890703/178039647-2fefa46f-11c1-48fe-8052-e4fa42695dcc.png)

I wasn't aware this was broken and will need to look into it.

**Comment by EricWittmann** [comment] 2022-07-08 17:18
Ah OK I have figured out the problem.  I'm guessing you chose "YAML" format when trying to publish.  Right now the conversion to YAML is broken.  For more info go here:

https://github.com/Apicurio/apicurio-studio/issues/1925

This will be fixed in the next release.

**Comment by EricWittmann** [comment] 2022-07-08 17:18
If you can confirm that you can **successfully** Publish your API in `JSON` format that would be helpful.  We could close this issue as a duplicate.

**Comment by lhuria94** [comment] 2022-07-11 04:52
Yes, thanks for looking into this. 
Publishing `API` in JSON works fine.

Do we generally have a timeline to fix YAML one, like when is the next release planned?

**Comment by EricWittmann** [comment] 2022-08-10 19:30
We just need to do final testing of the migration from Thorntail to Quarkus.  It's taking longer than normal due to summer vacations on the team.  :)

Once everyone is back in action we'll get things fixed.  But it might not be until the end of August or even early September.  :(

**Comment by AraConnect** [comment] 2022-08-12 07:38
I have also the same problem, so I am waiting for the next release.

**Comment by EricWittmann** [comment] 2022-08-16 15:55
Hoping to get a release done next week.  Thank you for your patience.

Closing as a duplicate of https://github.com/Apicurio/apicurio-studio/issues/1925

**Closed by EricWittmann** 2022-08-16 15:55 UTC
Labels: question, component/studio, priority/normal
