### ISSUE TITLE
Missing braces on value inside Example object

### ISSUE THREAD

**Issue by sercastiGL** [Apicurio/apicurio-studio#737] opened 2019-04-17 16:05 UTC
Following the OpenAPI spec here: https://github.com/Apicurio/OpenAPI-Specification/blob/master/versions/3.0.0.md#exampleObject

the Example object uses a value field, which should use braces { } 

Currently generating an example for a single object with apicurio generates this:

```yaml
    examples:
        MyExample:
            value:
                -
                    id: 1
                    name: Carol
                    lastname: Danvers
                    email: carol.danvers@gmail.com
                    mentor: Ororo Munroe
                    lastConnection: '2019-01-11'
                    avatarId: 1
```

Which fails to be interpreted as a valid mock example response by microcks, as it is non-spec compatible

Correct syntax is:

```yaml
    examples:
        MyExample:
            value:  {
                -
                    id: 1
                    name: Carol
                    lastname: Danvers
                    email: carol.danvers@gmail.com
                    mentor: Ororo Munroe
                    lastConnection: '2019-01-11'
                    avatarId: 1
            }
```

**Comment by EricWittmann** [comment] 2019-04-18 12:58
I have some questions/thoughts:

1) Great sample data.
B) what does this look like in Apicurio if you switch the source type to JSON?
III) What exactly did you enter in the example dialog to achieve this?  Aka - how do I reproduce this result?

**Comment by lbroudoux** [comment] 2019-04-23 07:57
Hi @EricWittmann and @sercastiGL,

FYI, I've made extensive tests and enhancements on the Microcks side regarding this question of examples formatting. Things are related to issue https://github.com/microcks/microcks/issues/134#issuecomment-485679926 

Seems like in previous releases all examples were formated using a String containing JSON whatever maybe the format of the OpenAPI Spec (YAML or JSON). In recent releases, examples format is now aligned on OpenAPI Spec format even if examples were specified using JSON string. This seems to be the case for examples bound to request or response, not those bound to data types.

**Comment by lbroudoux** [comment] 2019-04-23 07:57
Hi @EricWittmann and @sercastiGL,

FYI, I've made extensive tests and enhancements on the Microcks side regarding this question of examples formatting. Things are related to issue https://github.com/microcks/microcks/issues/134#issuecomment-485679926 

Seems like in previous releases all examples were formatted using a String containing JSON whatever maybe the format of the OpenAPI Spec (YAML or JSON). In recent releases, examples format is now aligned on OpenAPI Spec format even if examples were specified using JSON string. This seems to be the case for examples bound to request or response, not those bound to data types.

**Comment by EricWittmann** [comment] 2019-04-23 12:15
You are right, @lbroudoux - previous apicurio releases stored the examples as strings.  But recently we've changed to using objects when possible, because most of the downstream tooling expects that.  Apologies for the breakage on the Microcks side.

All of that said, I'm unsure about whether this issue is a bug or not.  I'll wait for clarifying information from @sercastiGL before I close this as "not a bug", though. :)

**Comment by sercastiGL** [comment] 2019-04-24 20:03
Ok, steps to reproduce:
a) enter apicurio, create new API: https://studio.apicur.io/apis/create
b) edit the api you just created: https://studio.apicur.io/apis/_apiId_/editor
c) add a new path: /api/notifications
d) add a Get operation to that path
e) add a Response to that path
f) add a media type to that response: application/json
g) add an example to that response:
```
{
    "id": "1"
}
```
If I switch to json, this is what I get
<img width="344" alt="Screen Shot 2019-04-24 at 17 02 07" src="https://user-images.githubusercontent.com/44201412/56690005-cfeae380-66b2-11e9-8a26-b497d4ed6c2f.png">
<img width="732" alt="Screen Shot 2019-04-24 at 17 01 25" src="https://user-images.githubusercontent.com/44201412/56690013-d5482e00-66b2-11e9-9057-9d3937dcc32e.png">

**Comment by EricWittmann** [comment] 2019-04-25 00:50
OK thank you for clarifying.  I actually do not think this is a bug in Apicurio, but rather something that Microcks must handle better.  The Microcks issue that @lbroudoux mentioned is here:  https://github.com/microcks/microcks/issues/134

What you're seeing in the source code is actually OK.  When storing an example as an object (rather than as a string), the formatting of the source will be valid YAML.  The OpenAPI spec allows the example value to be either a string or an object.  In this case we're storing it as an object, and the serialization of that content to YAML is fine.  If you switch to JSON in the source tab you'll see a different syntax.

In any case, this is not a bug, and we just need to wait for an update to Microcks for this to be fixed.

**Comment by lbroudoux** [comment] 2019-04-25 07:48
Agreed. Enhancements have been pushed to master branch and should be present into `latest` Microcks image. I'll close the Microcks issue in a few tests ...

**Comment by EricWittmann** [comment] 2019-04-25 10:37
Awesome - thanks @lbroudoux and sorry for changing/breaking this without mentioning it to you.  I'll try to keep that in mind in the future for any changes to examples.

**Closed by EricWittmann** 2019-04-25 10:37 UTC
Labels: bug
