### ISSUE TITLE
Warning "Schema items must be present only for schemas of type 'array' " is promoted when adding a parameter through UI -- openapi: 3.0.2

### ISSUE THREAD

**Issue by yuanhuiliu** [Apicurio/apicurio-studio#785] opened 2019-05-29 08:59 UTC
"Schema items must be present only for schemas of type 'array'  " is promoted when adding path parameters, query parameters or header parameters through UI. The screenshot of warning and code is as follows:
![paramsError](https://user-images.githubusercontent.com/16347556/58543718-93228700-8232-11e9-8333-3ec8d0c85bdc.png)

The warning will disappear when updating anything in Open API source code and save it, such as description.

**Comment by Ranbato** [comment] 2019-06-11 22:36
I see this all the time as well.  Let me know if you need a sample

**Comment by EricWittmann** [comment] 2019-06-12 10:59
A sample would be great, thanks.

**Comment by Ranbato** [comment] 2019-06-13 21:03
[Test API.yaml.zip](https://github.com/Apicurio/apicurio-studio/files/3288091/Test.API.yaml.zip)

This is the smallest example I can make.  Note that after exporting the file it no longer shows the error in the UI, but if I delete and re-add the response the error shows up again.
It also shows up if I mark anything as required.

**Comment by EricWittmann** [comment] 2019-06-14 10:38
Thanks.

**Comment by EricWittmann** [comment] 2019-06-19 16:47
I can not reproduce this with the latest version of Apicurio.  Admittedly a large number of changes have been made to both editing and validation, so it is possible that this has simply been fixed.

It's also possible I'm simply missing something.  I'm going to close this for now, but I would very much appreciate it if someone could re-open it if the next release of Apicurio (will be done this week) still exhibits this problem.

**Closed by EricWittmann** 2019-06-19 16:47 UTC
Labels: bug

**Comment by brandonjmckay** [comment] 2019-06-19 17:17
@EricWittmann What's the latest version? I'm on the site right now and I'm experiencing this issue still.

**Comment by EricWittmann** [comment] 2019-06-19 17:26
The online version is not the latest.  That said if you could screencast
yourself reproducing it that would be super helpful.

**Comment by brandonjmckay** [comment] 2019-06-19 17:36
Any specific steps do you want me to record?

**Comment by EricWittmann** [comment] 2019-06-19 17:40
No.  Anything you can do to reproduce it would be awesome.  Especially from
an empty document.

**Comment by brandonjmckay** [comment] 2019-06-19 21:41
![apicurio-schemaerror-sm](https://user-images.githubusercontent.com/1518678/59803417-40237900-92a0-11e9-94fa-e79acb349910.gif)

**Comment by yuanhuiliu** [comment] 2019-06-20 07:17
Add the screencast to reproduce this issue for the online version.
![array-error](https://user-images.githubusercontent.com/16347556/59828863-7d563c80-936e-11e9-894d-45b56373fb73.gif)

**Comment by EricWittmann** [comment] 2019-06-20 13:17
Thanks!

**Comment by EricWittmann** [comment] 2019-06-20 13:23
OK I have now been able to reproduce this (thanks for the videos!) in the online version (which is older) but cannot reproduce this with the latest version on master.  I'm going to leave this closed for now and will be doing a new release today or tomorrow (which will result in the online version being updated).  So hopefully this will be resolved.  The data modeling, validation, and editing commands have all been massively changed, so I'm guessing we'll see other problems instead. :)

**Comment by yuanhuiliu** [comment] 2019-06-21 02:08
Thank, I will try the new version after it is released.

**Comment by EricWittmann** [comment] 2019-06-21 12:15
The new version has been released and is available at https://studio.apicur.io if you'd like to give it a try.
