### ISSUE TITLE
Latest Image Released Jun. 2 breaks syncing with Microcks

### ISSUE THREAD

**Issue by deanpeterson** [Apicurio/apicurio-studio#1927] opened 2022-06-10 18:33 UTC
Ever since the underlying image in the apicurio image stream updated on June 2, I get the following errors syncing to microcks: https://gist.github.com/deanpeterson/2c4f0ec4ccbad995fe13ff9b37ca431f

**Comment by fbuinosquy1985** [comment] 2022-06-10 18:42
yes is the same error that i opened a issue here https://github.com/Apicurio/apicurio-studio/issues/1925

**Comment by deanpeterson** [comment] 2022-06-10 18:58
I spoke with a principal software engineer on the team and they have acknowledged the bug. The fix will be coming very shortly.

**Comment by mhagnumdw** [comment] 2022-07-01 20:11
Same error here! Any news? Tks!

**Comment by GeneralLuzi** [comment] 2022-08-04 10:34
hey @EricWittmann any news on that? Thanks!

**Comment by EricWittmann** [comment] 2022-08-18 16:02
Sorry this is taking so long.  We should have a new release based on Quarkus next week.  We've had some competing priorities and some vacations that have delayed things a bit.

**Comment by EricWittmann** [comment] 2022-08-18 16:02
BTW I'm going to close this as a duplicate of https://github.com/Apicurio/apicurio-studio/issues/1925

**Closed** 2022-08-18 16:02 UTC
