### ISSUE TITLE
Using Postman with Apicurio Studio

### ISSUE THREAD

**Issue by Dhruvsakhuja** [Apicurio/apicurio-studio#2000] opened 2022-09-07 06:07 UTC
Not able to generate OAuth 2.0 token and also document is outdated for the same.

**Comment by Stwissel** [comment] 2022-09-08 16:10
@Dhruvsakhuja Can you share more details? What steps did you take, what did you expect and what happened instead. The steps should enable anyone to reproduce your issue.

"Not able" leaves anyone guessing and diminishes your chance of any resolution.

**Comment by Dhruvsakhuja** [comment] 2022-09-21 10:29
So I wanted to ask if I want to generate Oauth 2.0 access token, what all fields should i pass in order to get the token.
currently I am passing 
1. Token Name : Apicurio Studio API (localhost)
2. Grant Type : Authorization Code 
3. Callback URL : https://oauth.pstmn.io/v1/callback
4. Auth URL : http://localhost:8080/?redirect_uri=https://oauth.pstmn.io/v1/callback&response_type=code&client_id=apicurio-studio
5. Access Token URL : [http://lo
calhost:8080/auth/realms/apicurio-local/protocol/openid-connect/token](http://localhost:8080/auth/realms/apicurio-local/protocol/openid-connect/token)
6. Client ID : apicurio-studio

And according to documentation, passing "http://localhost:8080/api-hub/system/status" this as the request URL. But still token is not getting generated.

<img width="1440" alt="Screenshot 2022-09-21 at 3 55 56 PM" src="https://user-images.githubusercontent.com/43448338/191481599-583a8205-dd15-458b-8d63-f4006a0f2b56.png">

**Comment by Dhruvsakhuja** [comment] 2022-09-26 04:33
@carlesarnal can you help me regarding this issue?

**Comment by Dhruvsakhuja** [comment] 2022-09-27 07:41
@EricWittmann can someone help me with this issue or update is someone is looking into it ?

**Comment by carlesarnal** [comment] 2022-09-27 07:48
Hi @Dhruvsakhuja, I will start looking into this today, I'll get back to you as soon as I have any updates.

**Comment by carlesarnal** [comment] 2022-09-27 07:49
In any case, calling system status you won't get the token since that endpoint is not protected, thus why you're getting a 200.

**Comment by Dhruvsakhuja** [comment] 2022-09-27 10:03
@carlesarnal 

> In any case, calling system status you won't get the token since that endpoint is not protected, thus why you're getting a 200.
Yes, that i figured out.


> Hi @Dhruvsakhuja, I will start looking into this today, I'll get back to you as soon as I have any updates.

Thanks @carlesarnal.

**Comment by Dhruvsakhuja** [comment] 2022-09-30 05:29
@carlesarnal got any updates?

**Comment by carlesarnal** [comment] 2022-09-30 08:39
> @carlesarnal got any updates?

No, hadn't had the time to go through this, have you tried a different endpoint?

**Comment by Dhruvsakhuja** [comment] 2022-09-30 08:49
> > @carlesarnal got any updates?
> 
> No, hadn't had the time to go through this, have you tried a different endpoint?

No, it was not actually checking any endpoint while generating the token. When i click grant new token, it redirect to the auth url in a browser, and not getting authenticated to generate the token.

**Comment by carlesarnal** [comment] 2022-09-30 09:00
It works with no issues, just don't use the authorize using browser option and instead redirect to the application itself (or if you want to use the authorize using browser option, add the postman URL to the valid redirect URLs in Keycloak). Here you have the configuration I used to test the usecase.

![imagen](https://user-images.githubusercontent.com/12640103/193234123-7abe2369-7220-4255-bcdb-23e778155028.png)

**Comment by Dhruvsakhuja** [comment] 2022-09-30 09:23
> It works with no issues, just don't use the authorize using browser option and instead redirect to the application itself (or if you want to use the authorize using browser option, add the postman URL to the valid redirect URLs in Keycloak, otherwise you'll get an invalid redirect error). Here you have the configuration I used to test the use case.
> 
> ![imagen](https://user-images.githubusercontent.com/12640103/193234123-7abe2369-7220-4255-bcdb-23e778155028.png)

I am trying with the same configuration but i am getting the following error.

<img width="1007" alt="Screenshot 2022-09-30 at 2 51 36 PM" src="https://user-images.githubusercontent.com/43448338/193238719-1af90993-a87d-47d9-8a82-bc41bf2ef78c.png">

**Comment by carlesarnal** [comment] 2022-09-30 09:25
As Postman is telling you, please, check the console so we can have more details. Note that this flow will open a new window and you need to login there with a valid set of credentials.

**Comment by Dhruvsakhuja** [comment] 2022-09-30 09:28
> As Postman is telling you, please, check the console so we can have more details. Note that this flow will open a new window and you need to login there with a valid set of credentials.

yes, for me this flow is trying to open a new window but then this error pops up. Console is showing the following : 
<img width="1424" alt="Screenshot 2022-09-30 at 2 57 33 PM" src="https://user-images.githubusercontent.com/43448338/193239883-356131bf-3387-479c-be4b-5523e0e54191.png">

**Comment by carlesarnal** [comment] 2022-09-30 09:56
I'm sorry but you'll need to play a bit more with it since that output is not very helpful and I cannot reproduce the error on my end. Try to create a completely empty postman request and then try to request the token perhaps.

**Comment by EricWittmann** [comment] 2022-10-04 19:55
Perhaps something is preventing the popup window?

**Comment by Dhruvsakhuja** [comment] 2022-10-06 07:31
> Perhaps something is preventing the popup window?

@EricWittmann I have checked that part as well only for these specific configurations i am not getting pop-up window.

**Comment by EricWittmann** [comment] 2022-12-20 12:32
We're not sure what else to add to this issue.  The configuration @carlesarnal shared works - he's confirmed and I have as well.  Not sure why yours is not working.  Perhaps a Postman issue of some kind? 

Closing.  If you think we can help more please re-open.

**Closed by EricWittmann** 2022-12-20 12:32 UTC
