### ISSUE TITLE
How to tag an api operation?

### ISSUE THREAD

**Issue by allanic79** [Apicurio/apicurio-studio#333] opened 2018-07-04 05:25 UTC
I created several tags on top level. But I didn't find a way to apply them on individual api. For example, to add "tags" under operation level like below: 
```
  /path:
    get:
      tags:
      - some_tag
      summary: 
```
Is it currently possible?

**Comment by EricWittmann** [comment] 2018-07-04 18:54
Unfortunately that's one of those features that just hasn't been done yet. :(

For now, you can work around this by editing the source directly.  But editing/managing the tags for an Operation is coming in the near future.

**Comment by EricWittmann** [comment] 2018-08-02 16:10
I should be working on this pretty soon.  We have a UX design for it and it's relatively high on the queue (and not very hard to implement). :)

**Comment by gigaga** [comment] 2018-08-03 08:58
Great!

**Comment by EricWittmann** [comment] 2018-09-21 17:48
This is a duplicate of https://github.com/Apicurio/apicurio-studio/issues/117 - closing this and working on #117. :)

**Closed by EricWittmann** 2018-09-21 17:48 UTC
Labels: enhancement
