### ISSUE TITLE
Forbidden Error while setting development set up

### ISSUE THREAD

**Issue by SarvaniVarma** [Apicurio/apicurio-studio#357] opened 2018-07-25 04:29 UTC
While setting development environment with the latest code I get "forbidden error" when accessing the application.
Previously it was working fine with the old code when tried it with latest code, I get this error.
![forbidden](https://user-images.githubusercontent.com/41433069/43179544-28e1b232-8ff1-11e8-989c-301a89259cb7.png)

Server Log:

[server log](https://github.com/Apicurio/apicurio-studio/files/2226482/server.log)

**Comment by EricWittmann** [comment] 2018-07-25 11:56
Are you using the cloud version of Keycloak or do you have your own?  I suspect this is a duplicate of this issue:  https://github.com/Apicurio/apicurio-studio/issues/356

**Comment by SarvaniVarma** [comment] 2018-07-25 12:03
I am using cloud version of keycloak.

**Comment by EricWittmann** [comment] 2018-07-25 12:10
OK thanks.  I'm taking a look at this now to see if I can reproduce it locally.

**Comment by EricWittmann** [comment] 2018-07-25 12:17
@SarvaniVarma I'm going to close this issue as a duplicate of #356 - let's have a discussion over there. :)

**Closed** 2018-07-25 13:59 UTC
