### ISSUE TITLE
Editor: schema allOf doesn't render in UI, throws error on preview

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#1030] opened 2020-01-10 16:37 UTC
Trying to import a OpenAPI definition that makes heavy use of the `allOf` keyword. I have a method that looks like this:

```yaml
 /messages/{messageIds}:
    get:
      tags:
        - messages
      summary: Get messages. Support multiple message
        ids, comma separated.
      operationId: messages.fetchMessages
      parameters:
        - $ref: '#/components/parameters/headerAuthorization'
        - $ref: '#/components/parameters/pathMessageIds'
        - $ref: '#/components/parameters/queryFormat'
      responses:
        200:
          description: Query request succeeded
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBaseStructure'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/MessagesMultiStatus"
```
However the Response doesn't show a data type configured:

![Screenshot of response](https://user-images.githubusercontent.com/542549/72169050-52fec600-3409-11ea-9ce6-6d068cd6e1f4.png)

The schema part looks like this:

```yaml
MessagesMultiStatus:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/MultiStatusMustHave'
          - $ref: '#/components/schemas/Message'
ResponseBaseStructure:
      properties:
        data:
          type: array
          items:
            type: object
        metadata:
          type: object
          required:
            - message
            - reqId
          properties:
            message:
              type: string
            reqId:
              type: string
```
Then the preview throws the error:

```
Something went wrong...
Incompatible types in allOf at "/properties/data/items"
Stack trace
Error: Incompatible types in allOf at "/properties/data/items"
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:116:46818)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:116:47178)
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:116:47021)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:116:50046)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:116:57514)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:116:58884
    at Array.map (<anonymous>)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:116:58832)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:116:59814)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:116:62842

ReDoc Version: 2.0.0-rc.20
Commit: fd581261
```

Swagger Editor loads and displays it. What do I miss?

**Comment by EricWittmann** [comment] 2020-01-10 17:03
There are two separate things here.  Apicurio Editor does not (currently) support inline schemas in e.g. response content.  If you were to extract that inline schema into its own Schema Definition and then reference it from the Reponse, then Apicurio would recognize it properly.  That's simply missing functionality at the moment.  We should handle that (and other) use cases better than we do.

As for the preview - that is an issue with ReDoc (which we use to render/preview the documentation).  You'll need to write up an issue there:  https://github.com/Redocly/redoc/issues

It seems ReDoc probably doesn't like the fact that your base type and your extended inline type both have `data` properties.  That's my best guess anyway.

**Comment by EricWittmann** [comment] 2020-01-10 17:06
I'm going to mark this is a duplicate of this issue:  https://github.com/Apicurio/apicurio-studio/issues/744

**Closed by EricWittmann** 2020-01-10 17:06 UTC
Labels: editor, enhancement

**Comment by Stwissel** [comment] 2020-01-13 10:33
Hi Eric,
thx for the detailed explanation. I moved my schema content out of the method (which is cleaner that mixing methods and schema, so I'm good with that part). However the schema editor doesn't seem to have an UI for composite arrays. So when I have:

```yaml
type: array
items:
    allOf:
        -
            $ref: '#/components/schemas/MultiStatusMustHave'
        -
            $ref: '#/components/schemas/Message'
```
The editor UI would show `Type: Array` with no Type specified. What should I do here?

**Comment by EricWittmann** [comment] 2020-01-13 18:50
Hm that's yet another use-case that we're not covering. :(  There are so many different things you can do in JSON schema!

What you ~~can do~~ **should be able to do** in Apicurio Studio is create another schema e.g. `MessageWithMultiStatus` which models the composite object, and then use that as the type of the array.

I'll open up a separate issue to add support for composite arrays, as I'm guessing that's not an uncommon use-case:  https://github.com/Apicurio/apicurio-studio/issues/1032
