### ISSUE TITLE
No UI support for OAI 3 Responses

### ISSUE THREAD

**Issue by DeeGeeMan** [Apicurio/apicurio-studio#834] opened 2019-07-03 14:08 UTC
There is no UI support for components object for **responses** like **schemas**.
https://swagger.io/specification/#componentsObject

**Comment by EricWittmann** [comment] 2019-07-03 14:46
Duplicate of:  https://github.com/Apicurio/apicurio-studio/issues/96

**Closed by EricWittmann** 2019-07-03 14:46 UTC
