### ISSUE TITLE
Editor:  support $refs for parameter schemas

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#932] opened 2019-10-04 13:43 UTC
Right now the UI does not allow the user to specify a schema reference when defining a type for a parameter.  I think that was not supported in OAI 2.  But it is allowed in OAI 3 and the UI should support it.

**Comment by schelv** [comment] 2021-08-09 14:38
Is this a duplicate of #241 ?

**Comment by EricWittmann** [comment] 2021-08-20 13:38
Agreed, thank you.

**Closed** 2021-08-20 13:38 UTC
Labels: duplicate, enhancement, editor
