### ISSUE TITLE
Mock with Microcks - Unexpected Error on Page()

### ISSUE THREAD

**Issue by SJWooten** [Apicurio/apicurio-studio#849] opened 2019-07-18 22:07 UTC
Using the docker-compose distro. Created new API with the latest version of OpenAPI and followed the YouTube video to mock the Test api and received Unexpected Error on Page() instead of the API mocked successfully page. I've also tried sample and pet store with no luck. So what am I missing? Working on a POC for API-first development with JHipster. Below is all I am seeing in the logs.

2019-07-18 21:53:14,878 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-62) Selecting mock activity for API Design: 6 from 0 to 20,
2019-07-18 21:53:14,878 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-57) Getting a list of all permissions (collaborators) for API: 6.,
2019-07-18 21:53:14,877 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-57) Retrieving all collaborators for API: 6,
2019-07-18 21:53:14,828 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-62) Getting an API design with ID 6,

**Comment by EricWittmann** [comment] 2019-07-19 11:25
Do you see any errors in the browser console when this happens?

**Comment by EricWittmann** [comment] 2019-07-19 13:45
I just tried a fresh installation on my centos 7 box using docker compose and everything worked as expected for me:

![image](https://user-images.githubusercontent.com/1890703/61539626-e8487100-aa09-11e9-8a18-807df3351080.png)

Hopefully there is an error message of some kind available to you in the browser/javascript console.

**Comment by SJWooten** [comment] 2019-07-19 14:25
I'll check, this is a straight install via docker-compose and is running on AWS EC2 instance and my Mac laptop. Both have the same issue.

Get Outlook for Android

________________________________

**Comment by SJWooten** [comment] 2019-07-19 14:53
Here are the errors from the browser console.

[MockPageComponent] Error getting API def main.1bb9561… .js:1

Error: Error: Unknown document type: [object Object]

at Function.e.createDocument (main.1bb9561d57f59e88ae88.js:1)

at main.1bb9561d57f59e88ae88.js:1

at e.invoke (polyfills.9c67d1be23abf75fea1a.js:1)

at Object.onInvoke (main.1bb9561d57f59e88ae88.js:1)

at e.invoke (polyfills.9c67d1be23abf75fea1a.js:1)

at  t.run<http://t.run> (polyfills.9c67d1be23abf75fea1a.js:1)

at polyfills.9c67d1be23abf75fea1a.js:1

at e.invokeTask (polyfills.9c67d1be23abf75fea1a.js:1)

at Object.onInvokeTask (main.1bb9561d57f59e88ae88.js:1)

at e.invokeTask (polyfills.9c67d1be23abf75fea1a.js:1)

ERROR TypeError: Cannot read property 'message' of undefined

at e.errorMessage (main.1bb9561d57f59e88ae88.js:1)

at Object.updateRenderer (main.1bb9561d57f59e88ae88.js:1)

at Object.updateRenderer (main.1bb9561d57f59e88ae88.js:1)

at wl (main.1bb9561d57f59e88ae88.js:1)

at Dl (main.1bb9561d57f59e88ae88.js:1)

at Tl (main.1bb9561d57f59e88ae88.js:1)

at wl (main.1bb9561d57f59e88ae88.js:1)

at Dl (main.1bb9561d57f59e88ae88.js:1)

at Al (main.1bb9561d57f59e88ae88.js:1)

at wl (main.1bb9561d57f59e88ae88.js:1)



Get Outlook for Android

________________________________

**Comment by EricWittmann** [comment] 2019-07-19 14:59
I think this is a duplicate of this issue:  https://github.com/Apicurio/apicurio-studio/issues/835

Which has since been fixed.  Can you verify which version of Apicurio you are running?  The latest version (0.2.30.Final) should have this fixed.

**Comment by SJWooten** [comment] 2019-07-19 15:34
Docker is pulling the latest-release. At the time I ran the docker-compose, 7/10, I think it was 2.29.Final. The container image is tagged with latest-release. Looks like 2.30 just came out 3 days ago?

Get Outlook for Android

________________________________

**Comment by SJWooten** [comment] 2019-07-19 16:00
2.30.Final does indeed fix the problem.

Thanks,

Steve

Get Outlook for Android

________________________________

**Comment by EricWittmann** [comment] 2019-07-19 18:22
Awesome - glad to hear it.

**Closed by EricWittmann** 2019-07-19 18:22 UTC
Labels: bug
